// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: metadata_service.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeekPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ByteOffset    int64                  `protobuf:"varint,2,opt,name=byte_offset,json=byteOffset,proto3" json:"byte_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeekPoint) Reset() {
	*x = SeekPoint{}
	mi := &file_metadata_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekPoint) ProtoMessage() {}

func (x *SeekPoint) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekPoint.ProtoReflect.Descriptor instead.
func (*SeekPoint) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{0}
}

func (x *SeekPoint) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SeekPoint) GetByteOffset() int64 {
	if x != nil {
		return x.ByteOffset
	}
	return 0
}

type UpdateMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	Duration      float64                `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	SeekPoints    []*SeekPoint           `protobuf:"bytes,3,rep,name=seek_points,json=seekPoints,proto3" json:"seek_points,omitempty"`
	Waveform      []float32              `protobuf:"fixed32,4,rep,packed,name=waveform,proto3" json:"waveform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetaRequest) Reset() {
	*x = UpdateMetaRequest{}
	mi := &file_metadata_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetaRequest) ProtoMessage() {}

func (x *UpdateMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetaRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetaRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetaRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *UpdateMetaRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UpdateMetaRequest) GetSeekPoints() []*SeekPoint {
	if x != nil {
		return x.SeekPoints
	}
	return nil
}

func (x *UpdateMetaRequest) GetWaveform() []float32 {
	if x != nil {
		return x.Waveform
	}
	return nil
}

type GetStreamDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamDataRequest) Reset() {
	*x = GetStreamDataRequest{}
	mi := &file_metadata_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamDataRequest) ProtoMessage() {}

func (x *GetStreamDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamDataRequest.ProtoReflect.Descriptor instead.
func (*GetStreamDataRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetStreamDataRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

type StreamDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	Duration      float64                `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	SeekPoints    []*SeekPoint           `protobuf:"bytes,3,rep,name=seek_points,json=seekPoints,proto3" json:"seek_points,omitempty"`
	Waveform      []float32              `protobuf:"fixed32,4,rep,packed,name=waveform,proto3" json:"waveform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDataResponse) Reset() {
	*x = StreamDataResponse{}
	mi := &file_metadata_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDataResponse) ProtoMessage() {}

func (x *StreamDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDataResponse.ProtoReflect.Descriptor instead.
func (*StreamDataResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{3}
}

func (x *StreamDataResponse) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *StreamDataResponse) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *StreamDataResponse) GetSeekPoints() []*SeekPoint {
	if x != nil {
		return x.SeekPoints
	}
	return nil
}

func (x *StreamDataResponse) GetWaveform() []float32 {
	if x != nil {
		return x.Waveform
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_metadata_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{4}
}

var File_metadata_service_proto protoreflect.FileDescriptor

const file_metadata_service_proto_rawDesc = "" +
	"\n" +
	"\x16metadata_service.proto\x12\x10metadata_service\"J\n" +
	"\tSeekPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x12\x1f\n" +
	"\vbyte_offset\x18\x02 \x01(\x03R\n" +
	"byteOffset\"\xa2\x01\n" +
	"\x11UpdateMetaRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\x12<\n" +
	"\vseek_points\x18\x03 \x03(\v2\x1b.metadata_service.SeekPointR\n" +
	"seekPoints\x12\x1a\n" +
	"\bwaveform\x18\x04 \x03(\x02R\bwaveform\"/\n" +
	"\x14GetStreamDataRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\"\xa3\x01\n" +
	"\x12StreamDataResponse\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\x12<\n" +
	"\vseek_points\x18\x03 \x03(\v2\x1b.metadata_service.SeekPointR\n" +
	"seekPoints\x12\x1a\n" +
	"\bwaveform\x18\x04 \x03(\x02R\bwaveform\"\x0f\n" +
	"\rEmptyResponse2\xcd\x01\n" +
	"\x0fMetadataService\x12[\n" +
	"\x13UpdateTechnicalMeta\x12#.metadata_service.UpdateMetaRequest\x1a\x1f.metadata_service.EmptyResponse\x12]\n" +
	"\rGetStreamData\x12&.metadata_service.GetStreamDataRequest\x1a$.metadata_service.StreamDataResponseB7Z5Music_Streaming_System/packages/shared-proto/metadatab\x06proto3"

var (
	file_metadata_service_proto_rawDescOnce sync.Once
	file_metadata_service_proto_rawDescData []byte
)

func file_metadata_service_proto_rawDescGZIP() []byte {
	file_metadata_service_proto_rawDescOnce.Do(func() {
		file_metadata_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_service_proto_rawDesc), len(file_metadata_service_proto_rawDesc)))
	})
	return file_metadata_service_proto_rawDescData
}

var file_metadata_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metadata_service_proto_goTypes = []any{
	(*SeekPoint)(nil),            // 0: metadata_service.SeekPoint
	(*UpdateMetaRequest)(nil),    // 1: metadata_service.UpdateMetaRequest
	(*GetStreamDataRequest)(nil), // 2: metadata_service.GetStreamDataRequest
	(*StreamDataResponse)(nil),   // 3: metadata_service.StreamDataResponse
	(*EmptyResponse)(nil),        // 4: metadata_service.EmptyResponse
}
var file_metadata_service_proto_depIdxs = []int32{
	0, // 0: metadata_service.UpdateMetaRequest.seek_points:type_name -> metadata_service.SeekPoint
	0, // 1: metadata_service.StreamDataResponse.seek_points:type_name -> metadata_service.SeekPoint
	1, // 2: metadata_service.MetadataService.UpdateTechnicalMeta:input_type -> metadata_service.UpdateMetaRequest
	2, // 3: metadata_service.MetadataService.GetStreamData:input_type -> metadata_service.GetStreamDataRequest
	4, // 4: metadata_service.MetadataService.UpdateTechnicalMeta:output_type -> metadata_service.EmptyResponse
	3, // 5: metadata_service.MetadataService.GetStreamData:output_type -> metadata_service.StreamDataResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metadata_service_proto_init() }
func file_metadata_service_proto_init() {
	if File_metadata_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_service_proto_rawDesc), len(file_metadata_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metadata_service_proto_goTypes,
		DependencyIndexes: file_metadata_service_proto_depIdxs,
		MessageInfos:      file_metadata_service_proto_msgTypes,
	}.Build()
	File_metadata_service_proto = out.File
	file_metadata_service_proto_goTypes = nil
	file_metadata_service_proto_depIdxs = nil
}
