name = "finalizer"
main = "src/index.ts"
compatibility_date = "2026-05-01"
minify = true

[[queues.consumers]]
queue = "upload-events"
max_batch_size = 4
max_batch_timeout = 6
max_retries = 3
retry_delay = 16

[vars]
API_FINALIZE_URL = "https://marcus-pseudoscalar-unsurprisedly.ngrok-free.dev/api/v1/songs/internal/finalize-upload"
