// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: song_service.proto

package song

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SongStatus int32

const (
	SongStatus_SONG_STATUS_UNSPECIFIED SongStatus = 0
	SongStatus_SONG_STATUS_PENDING     SongStatus = 1 // Da tao record, cho worker xu ly
	SongStatus_SONG_STATUS_PROCESSING  SongStatus = 2 // Worker dang transcode/encrypt
	SongStatus_SONG_STATUS_READY       SongStatus = 3 // San sang phat
	SongStatus_SONG_STATUS_FAILED      SongStatus = 4 // Xu ly that bai
)

// Enum value maps for SongStatus.
var (
	SongStatus_name = map[int32]string{
		0: "SONG_STATUS_UNSPECIFIED",
		1: "SONG_STATUS_PENDING",
		2: "SONG_STATUS_PROCESSING",
		3: "SONG_STATUS_READY",
		4: "SONG_STATUS_FAILED",
	}
	SongStatus_value = map[string]int32{
		"SONG_STATUS_UNSPECIFIED": 0,
		"SONG_STATUS_PENDING":     1,
		"SONG_STATUS_PROCESSING":  2,
		"SONG_STATUS_READY":       3,
		"SONG_STATUS_FAILED":      4,
	}
)

func (x SongStatus) Enum() *SongStatus {
	p := new(SongStatus)
	*p = x
	return p
}

func (x SongStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SongStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_song_service_proto_enumTypes[0].Descriptor()
}

func (SongStatus) Type() protoreflect.EnumType {
	return &file_song_service_proto_enumTypes[0]
}

func (x SongStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SongStatus.Descriptor instead.
func (SongStatus) EnumDescriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{0}
}

// Lightweight summary for list/browse use cases
type SongSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Status        SongStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=song_service.SongStatus" json:"status,omitempty"`
	DurationSec   int32                  `protobuf:"varint,7,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongSummary) Reset() {
	*x = SongSummary{}
	mi := &file_song_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongSummary) ProtoMessage() {}

func (x *SongSummary) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongSummary.ProtoReflect.Descriptor instead.
func (*SongSummary) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{0}
}

func (x *SongSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SongSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SongSummary) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *SongSummary) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *SongSummary) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *SongSummary) GetStatus() SongStatus {
	if x != nil {
		return x.Status
	}
	return SongStatus_SONG_STATUS_UNSPECIFIED
}

func (x *SongSummary) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *SongSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Full detail for playback
type SongDetail struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist     string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Album      string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	UploaderId string                 `protobuf:"bytes,5,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	IsPublic   bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Status     SongStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=song_service.SongStatus" json:"status,omitempty"`
	// Output path for encrypted fMP4 on R2 Production
	EncryptedFilePath string `protobuf:"bytes,8,opt,name=encrypted_file_path,json=encryptedFilePath,proto3" json:"encrypted_file_path,omitempty"`
	// Basic technical metadata (heavy arrays stay in Metadata Service)
	DurationSec   int32  `protobuf:"varint,9,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	BitrateKbps   int32  `protobuf:"varint,10,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	Codec         string `protobuf:"bytes,11,opt,name=codec,proto3" json:"codec,omitempty"`   // ex: "aac"
	Format        string `protobuf:"bytes,12,opt,name=format,proto3" json:"format,omitempty"` // ex: "fmp4"
	CreatedAt     int64  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongDetail) Reset() {
	*x = SongDetail{}
	mi := &file_song_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongDetail) ProtoMessage() {}

func (x *SongDetail) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongDetail.ProtoReflect.Descriptor instead.
func (*SongDetail) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{1}
}

func (x *SongDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SongDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SongDetail) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *SongDetail) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *SongDetail) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *SongDetail) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *SongDetail) GetStatus() SongStatus {
	if x != nil {
		return x.Status
	}
	return SongStatus_SONG_STATUS_UNSPECIFIED
}

func (x *SongDetail) GetEncryptedFilePath() string {
	if x != nil {
		return x.EncryptedFilePath
	}
	return ""
}

func (x *SongDetail) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *SongDetail) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *SongDetail) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *SongDetail) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SongDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SongDetail) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Internal ingest metadata
type SongIngestInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status           SongStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=song_service.SongStatus" json:"status,omitempty"`
	SourceObjectPath string                 `protobuf:"bytes,3,opt,name=source_object_path,json=sourceObjectPath,proto3" json:"source_object_path,omitempty"`
	Checksum         string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	FileSizeBytes    int64                  `protobuf:"varint,5,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SongIngestInfo) Reset() {
	*x = SongIngestInfo{}
	mi := &file_song_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongIngestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongIngestInfo) ProtoMessage() {}

func (x *SongIngestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongIngestInfo.ProtoReflect.Descriptor instead.
func (*SongIngestInfo) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{2}
}

func (x *SongIngestInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SongIngestInfo) GetStatus() SongStatus {
	if x != nil {
		return x.Status
	}
	return SongStatus_SONG_STATUS_UNSPECIFIED
}

func (x *SongIngestInfo) GetSourceObjectPath() string {
	if x != nil {
		return x.SourceObjectPath
	}
	return ""
}

func (x *SongIngestInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *SongIngestInfo) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *SongIngestInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetSongRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SongId          string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	RequesterUserId string                 `protobuf:"bytes,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSongRequest) Reset() {
	*x = GetSongRequest{}
	mi := &file_song_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongRequest) ProtoMessage() {}

func (x *GetSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongRequest.ProtoReflect.Descriptor instead.
func (*GetSongRequest) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSongRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *GetSongRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

type GetSongByChecksumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      string                 `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongByChecksumRequest) Reset() {
	*x = GetSongByChecksumRequest{}
	mi := &file_song_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongByChecksumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongByChecksumRequest) ProtoMessage() {}

func (x *GetSongByChecksumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongByChecksumRequest.ProtoReflect.Descriptor instead.
func (*GetSongByChecksumRequest) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetSongByChecksumRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type GetSongByChecksumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *SongIngestInfo        `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongByChecksumResponse) Reset() {
	*x = GetSongByChecksumResponse{}
	mi := &file_song_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongByChecksumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongByChecksumResponse) ProtoMessage() {}

func (x *GetSongByChecksumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongByChecksumResponse.ProtoReflect.Descriptor instead.
func (*GetSongByChecksumResponse) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetSongByChecksumResponse) GetSong() *SongIngestInfo {
	if x != nil {
		return x.Song
	}
	return nil
}

func (x *GetSongByChecksumResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetSongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *SongDetail            `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongResponse) Reset() {
	*x = GetSongResponse{}
	mi := &file_song_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongResponse) ProtoMessage() {}

func (x *GetSongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongResponse.ProtoReflect.Descriptor instead.
func (*GetSongResponse) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetSongResponse) GetSong() *SongDetail {
	if x != nil {
		return x.Song
	}
	return nil
}

type GetSongIngestInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongIngestInfoRequest) Reset() {
	*x = GetSongIngestInfoRequest{}
	mi := &file_song_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongIngestInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongIngestInfoRequest) ProtoMessage() {}

func (x *GetSongIngestInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongIngestInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSongIngestInfoRequest) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetSongIngestInfoRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

type GetSongIngestInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *SongIngestInfo        `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongIngestInfoResponse) Reset() {
	*x = GetSongIngestInfoResponse{}
	mi := &file_song_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongIngestInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongIngestInfoResponse) ProtoMessage() {}

func (x *GetSongIngestInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongIngestInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSongIngestInfoResponse) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetSongIngestInfoResponse) GetSong() *SongIngestInfo {
	if x != nil {
		return x.Song
	}
	return nil
}

type ListSongsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Cursor          string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search          string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Artist          string                 `protobuf:"bytes,4,opt,name=artist,proto3" json:"artist,omitempty"`
	OnlyPublic      bool                   `protobuf:"varint,5,opt,name=only_public,json=onlyPublic,proto3" json:"only_public,omitempty"`
	RequesterUserId string                 `protobuf:"bytes,6,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSongsRequest) Reset() {
	*x = ListSongsRequest{}
	mi := &file_song_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSongsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSongsRequest) ProtoMessage() {}

func (x *ListSongsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSongsRequest.ProtoReflect.Descriptor instead.
func (*ListSongsRequest) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListSongsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListSongsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSongsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListSongsRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *ListSongsRequest) GetOnlyPublic() bool {
	if x != nil {
		return x.OnlyPublic
	}
	return false
}

func (x *ListSongsRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

type ListSongsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*SongSummary         `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSongsResponse) Reset() {
	*x = ListSongsResponse{}
	mi := &file_song_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSongsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSongsResponse) ProtoMessage() {}

func (x *ListSongsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSongsResponse.ProtoReflect.Descriptor instead.
func (*ListSongsResponse) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListSongsResponse) GetSongs() []*SongSummary {
	if x != nil {
		return x.Songs
	}
	return nil
}

func (x *ListSongsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListSongsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// API Gateway calls this after upload authorization / object registration
type CreateSongRecordRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Title      string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Artist     string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Album      string                 `protobuf:"bytes,3,opt,name=album,proto3" json:"album,omitempty"`
	UploaderId string                 `protobuf:"bytes,4,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	IsPublic   bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	// Quarantine object key/path on R2
	SourceObjectPath string `protobuf:"bytes,6,opt,name=source_object_path,json=sourceObjectPath,proto3" json:"source_object_path,omitempty"`
	FileSizeBytes    int64  `protobuf:"varint,7,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	Checksum         string `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSongRecordRequest) Reset() {
	*x = CreateSongRecordRequest{}
	mi := &file_song_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSongRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSongRecordRequest) ProtoMessage() {}

func (x *CreateSongRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSongRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateSongRecordRequest) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSongRecordRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSongRecordRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *CreateSongRecordRequest) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *CreateSongRecordRequest) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *CreateSongRecordRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *CreateSongRecordRequest) GetSourceObjectPath() string {
	if x != nil {
		return x.SourceObjectPath
	}
	return ""
}

func (x *CreateSongRecordRequest) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *CreateSongRecordRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type CreateSongRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *SongIngestInfo        `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	IngestJobId   string                 `protobuf:"bytes,2,opt,name=ingest_job_id,json=ingestJobId,proto3" json:"ingest_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSongRecordResponse) Reset() {
	*x = CreateSongRecordResponse{}
	mi := &file_song_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSongRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSongRecordResponse) ProtoMessage() {}

func (x *CreateSongRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSongRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateSongRecordResponse) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSongRecordResponse) GetSong() *SongIngestInfo {
	if x != nil {
		return x.Song
	}
	return nil
}

func (x *CreateSongRecordResponse) GetIngestJobId() string {
	if x != nil {
		return x.IngestJobId
	}
	return ""
}

// Worker calls this to finalize processing state
type UpdateSongProcessingResultRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SongId string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	Status SongStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=song_service.SongStatus" json:"status,omitempty"`
	// Present when READY
	EncryptedFilePath string `protobuf:"bytes,3,opt,name=encrypted_file_path,json=encryptedFilePath,proto3" json:"encrypted_file_path,omitempty"`
	DurationSec       int32  `protobuf:"varint,4,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	BitrateKbps       int32  `protobuf:"varint,5,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	Codec             string `protobuf:"bytes,6,opt,name=codec,proto3" json:"codec,omitempty"`
	Format            string `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	// Present when FAILED
	ErrorMessage  string `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSongProcessingResultRequest) Reset() {
	*x = UpdateSongProcessingResultRequest{}
	mi := &file_song_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSongProcessingResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSongProcessingResultRequest) ProtoMessage() {}

func (x *UpdateSongProcessingResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSongProcessingResultRequest.ProtoReflect.Descriptor instead.
func (*UpdateSongProcessingResultRequest) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSongProcessingResultRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *UpdateSongProcessingResultRequest) GetStatus() SongStatus {
	if x != nil {
		return x.Status
	}
	return SongStatus_SONG_STATUS_UNSPECIFIED
}

func (x *UpdateSongProcessingResultRequest) GetEncryptedFilePath() string {
	if x != nil {
		return x.EncryptedFilePath
	}
	return ""
}

func (x *UpdateSongProcessingResultRequest) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *UpdateSongProcessingResultRequest) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *UpdateSongProcessingResultRequest) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *UpdateSongProcessingResultRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *UpdateSongProcessingResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateSongProcessingResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSongProcessingResultResponse) Reset() {
	*x = UpdateSongProcessingResultResponse{}
	mi := &file_song_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSongProcessingResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSongProcessingResultResponse) ProtoMessage() {}

func (x *UpdateSongProcessingResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSongProcessingResultResponse.ProtoReflect.Descriptor instead.
func (*UpdateSongProcessingResultResponse) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateSongProcessingResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SongId        string                 `protobuf:"bytes,2,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteRequest) Reset() {
	*x = FavoriteRequest{}
	mi := &file_song_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteRequest) ProtoMessage() {}

func (x *FavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteRequest.ProtoReflect.Descriptor instead.
func (*FavoriteRequest) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{15}
}

func (x *FavoriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FavoriteRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

type FavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteResponse) Reset() {
	*x = FavoriteResponse{}
	mi := &file_song_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteResponse) ProtoMessage() {}

func (x *FavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteResponse.ProtoReflect.Descriptor instead.
func (*FavoriteResponse) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{16}
}

func (x *FavoriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Songs         []*SongSummary         `protobuf:"bytes,4,rep,name=songs,proto3" json:"songs,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_song_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{17}
}

func (x *Playlist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Playlist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Playlist) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Playlist) GetSongs() []*SongSummary {
	if x != nil {
		return x.Songs
	}
	return nil
}

func (x *Playlist) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Playlist) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetPlaylistRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId      string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	RequesterUserId string                 `protobuf:"bytes,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPlaylistRequest) Reset() {
	*x = GetPlaylistRequest{}
	mi := &file_song_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistRequest) ProtoMessage() {}

func (x *GetPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlaylistRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *GetPlaylistRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

type GetPlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistResponse) Reset() {
	*x = GetPlaylistResponse{}
	mi := &file_song_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistResponse) ProtoMessage() {}

func (x *GetPlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_song_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistResponse) Descriptor() ([]byte, []int) {
	return file_song_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetPlaylistResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

var File_song_service_proto protoreflect.FileDescriptor

const file_song_service_proto_rawDesc = "" +
	"\n" +
	"\x12song_service.proto\x12\fsong_service\"\xf2\x01\n" +
	"\vSongSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.song_service.SongStatusR\x06status\x12!\n" +
	"\fduration_sec\x18\a \x01(\x05R\vdurationSec\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\xb2\x03\n" +
	"\n" +
	"SongDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x1f\n" +
	"\vuploader_id\x18\x05 \x01(\tR\n" +
	"uploaderId\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\x120\n" +
	"\x06status\x18\a \x01(\x0e2\x18.song_service.SongStatusR\x06status\x12.\n" +
	"\x13encrypted_file_path\x18\b \x01(\tR\x11encryptedFilePath\x12!\n" +
	"\fduration_sec\x18\t \x01(\x05R\vdurationSec\x12!\n" +
	"\fbitrate_kbps\x18\n" +
	" \x01(\x05R\vbitrateKbps\x12\x14\n" +
	"\x05codec\x18\v \x01(\tR\x05codec\x12\x16\n" +
	"\x06format\x18\f \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"\xe3\x01\n" +
	"\x0eSongIngestInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.song_service.SongStatusR\x06status\x12,\n" +
	"\x12source_object_path\x18\x03 \x01(\tR\x10sourceObjectPath\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12&\n" +
	"\x0ffile_size_bytes\x18\x05 \x01(\x03R\rfileSizeBytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"U\n" +
	"\x0eGetSongRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\tR\x0frequesterUserId\"6\n" +
	"\x18GetSongByChecksumRequest\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\tR\bchecksum\"c\n" +
	"\x19GetSongByChecksumResponse\x120\n" +
	"\x04song\x18\x01 \x01(\v2\x1c.song_service.SongIngestInfoR\x04song\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"?\n" +
	"\x0fGetSongResponse\x12,\n" +
	"\x04song\x18\x01 \x01(\v2\x18.song_service.SongDetailR\x04song\"3\n" +
	"\x18GetSongIngestInfoRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\"M\n" +
	"\x19GetSongIngestInfoResponse\x120\n" +
	"\x04song\x18\x01 \x01(\v2\x1c.song_service.SongIngestInfoR\x04song\"\xbd\x01\n" +
	"\x10ListSongsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x16\n" +
	"\x06artist\x18\x04 \x01(\tR\x06artist\x12\x1f\n" +
	"\vonly_public\x18\x05 \x01(\bR\n" +
	"onlyPublic\x12*\n" +
	"\x11requester_user_id\x18\x06 \x01(\tR\x0frequesterUserId\"\x80\x01\n" +
	"\x11ListSongsResponse\x12/\n" +
	"\x05songs\x18\x01 \x03(\v2\x19.song_service.SongSummaryR\x05songs\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x8d\x02\n" +
	"\x17CreateSongRecordRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x03 \x01(\tR\x05album\x12\x1f\n" +
	"\vuploader_id\x18\x04 \x01(\tR\n" +
	"uploaderId\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12,\n" +
	"\x12source_object_path\x18\x06 \x01(\tR\x10sourceObjectPath\x12&\n" +
	"\x0ffile_size_bytes\x18\a \x01(\x03R\rfileSizeBytes\x12\x1a\n" +
	"\bchecksum\x18\b \x01(\tR\bchecksum\"p\n" +
	"\x18CreateSongRecordResponse\x120\n" +
	"\x04song\x18\x01 \x01(\v2\x1c.song_service.SongIngestInfoR\x04song\x12\"\n" +
	"\ringest_job_id\x18\x02 \x01(\tR\vingestJobId\"\xb7\x02\n" +
	"!UpdateSongProcessingResultRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.song_service.SongStatusR\x06status\x12.\n" +
	"\x13encrypted_file_path\x18\x03 \x01(\tR\x11encryptedFilePath\x12!\n" +
	"\fduration_sec\x18\x04 \x01(\x05R\vdurationSec\x12!\n" +
	"\fbitrate_kbps\x18\x05 \x01(\x05R\vbitrateKbps\x12\x14\n" +
	"\x05codec\x18\x06 \x01(\tR\x05codec\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\">\n" +
	"\"UpdateSongProcessingResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x0fFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\asong_id\x18\x02 \x01(\tR\x06songId\",\n" +
	"\x10FavoriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb8\x01\n" +
	"\bPlaylist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12/\n" +
	"\x05songs\x18\x04 \x03(\v2\x19.song_service.SongSummaryR\x05songs\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"a\n" +
	"\x12GetPlaylistRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\tR\x0frequesterUserId\"I\n" +
	"\x13GetPlaylistResponse\x122\n" +
	"\bplaylist\x18\x01 \x01(\v2\x16.song_service.PlaylistR\bplaylist*\x8d\x01\n" +
	"\n" +
	"SongStatus\x12\x1b\n" +
	"\x17SONG_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SONG_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16SONG_STATUS_PROCESSING\x10\x02\x12\x15\n" +
	"\x11SONG_STATUS_READY\x10\x03\x12\x16\n" +
	"\x12SONG_STATUS_FAILED\x10\x042\xc6\x06\n" +
	"\vSongService\x12F\n" +
	"\aGetSong\x12\x1c.song_service.GetSongRequest\x1a\x1d.song_service.GetSongResponse\x12d\n" +
	"\x11GetSongByChecksum\x12&.song_service.GetSongByChecksumRequest\x1a'.song_service.GetSongByChecksumResponse\x12d\n" +
	"\x11GetSongIngestInfo\x12&.song_service.GetSongIngestInfoRequest\x1a'.song_service.GetSongIngestInfoResponse\x12L\n" +
	"\tListSongs\x12\x1e.song_service.ListSongsRequest\x1a\x1f.song_service.ListSongsResponse\x12a\n" +
	"\x10CreateSongRecord\x12%.song_service.CreateSongRecordRequest\x1a&.song_service.CreateSongRecordResponse\x12\x7f\n" +
	"\x1aUpdateSongProcessingResult\x12/.song_service.UpdateSongProcessingResultRequest\x1a0.song_service.UpdateSongProcessingResultResponse\x12L\n" +
	"\vAddFavorite\x12\x1d.song_service.FavoriteRequest\x1a\x1e.song_service.FavoriteResponse\x12O\n" +
	"\x0eRemoveFavorite\x12\x1d.song_service.FavoriteRequest\x1a\x1e.song_service.FavoriteResponse\x12R\n" +
	"\vGetPlaylist\x12 .song_service.GetPlaylistRequest\x1a!.song_service.GetPlaylistResponseB3Z1Music_Streaming_System/packages/shared-proto/songb\x06proto3"

var (
	file_song_service_proto_rawDescOnce sync.Once
	file_song_service_proto_rawDescData []byte
)

func file_song_service_proto_rawDescGZIP() []byte {
	file_song_service_proto_rawDescOnce.Do(func() {
		file_song_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_song_service_proto_rawDesc), len(file_song_service_proto_rawDesc)))
	})
	return file_song_service_proto_rawDescData
}

var file_song_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_song_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_song_service_proto_goTypes = []any{
	(SongStatus)(0),                            // 0: song_service.SongStatus
	(*SongSummary)(nil),                        // 1: song_service.SongSummary
	(*SongDetail)(nil),                         // 2: song_service.SongDetail
	(*SongIngestInfo)(nil),                     // 3: song_service.SongIngestInfo
	(*GetSongRequest)(nil),                     // 4: song_service.GetSongRequest
	(*GetSongByChecksumRequest)(nil),           // 5: song_service.GetSongByChecksumRequest
	(*GetSongByChecksumResponse)(nil),          // 6: song_service.GetSongByChecksumResponse
	(*GetSongResponse)(nil),                    // 7: song_service.GetSongResponse
	(*GetSongIngestInfoRequest)(nil),           // 8: song_service.GetSongIngestInfoRequest
	(*GetSongIngestInfoResponse)(nil),          // 9: song_service.GetSongIngestInfoResponse
	(*ListSongsRequest)(nil),                   // 10: song_service.ListSongsRequest
	(*ListSongsResponse)(nil),                  // 11: song_service.ListSongsResponse
	(*CreateSongRecordRequest)(nil),            // 12: song_service.CreateSongRecordRequest
	(*CreateSongRecordResponse)(nil),           // 13: song_service.CreateSongRecordResponse
	(*UpdateSongProcessingResultRequest)(nil),  // 14: song_service.UpdateSongProcessingResultRequest
	(*UpdateSongProcessingResultResponse)(nil), // 15: song_service.UpdateSongProcessingResultResponse
	(*FavoriteRequest)(nil),                    // 16: song_service.FavoriteRequest
	(*FavoriteResponse)(nil),                   // 17: song_service.FavoriteResponse
	(*Playlist)(nil),                           // 18: song_service.Playlist
	(*GetPlaylistRequest)(nil),                 // 19: song_service.GetPlaylistRequest
	(*GetPlaylistResponse)(nil),                // 20: song_service.GetPlaylistResponse
}
var file_song_service_proto_depIdxs = []int32{
	0,  // 0: song_service.SongSummary.status:type_name -> song_service.SongStatus
	0,  // 1: song_service.SongDetail.status:type_name -> song_service.SongStatus
	0,  // 2: song_service.SongIngestInfo.status:type_name -> song_service.SongStatus
	3,  // 3: song_service.GetSongByChecksumResponse.song:type_name -> song_service.SongIngestInfo
	2,  // 4: song_service.GetSongResponse.song:type_name -> song_service.SongDetail
	3,  // 5: song_service.GetSongIngestInfoResponse.song:type_name -> song_service.SongIngestInfo
	1,  // 6: song_service.ListSongsResponse.songs:type_name -> song_service.SongSummary
	3,  // 7: song_service.CreateSongRecordResponse.song:type_name -> song_service.SongIngestInfo
	0,  // 8: song_service.UpdateSongProcessingResultRequest.status:type_name -> song_service.SongStatus
	1,  // 9: song_service.Playlist.songs:type_name -> song_service.SongSummary
	18, // 10: song_service.GetPlaylistResponse.playlist:type_name -> song_service.Playlist
	4,  // 11: song_service.SongService.GetSong:input_type -> song_service.GetSongRequest
	5,  // 12: song_service.SongService.GetSongByChecksum:input_type -> song_service.GetSongByChecksumRequest
	8,  // 13: song_service.SongService.GetSongIngestInfo:input_type -> song_service.GetSongIngestInfoRequest
	10, // 14: song_service.SongService.ListSongs:input_type -> song_service.ListSongsRequest
	12, // 15: song_service.SongService.CreateSongRecord:input_type -> song_service.CreateSongRecordRequest
	14, // 16: song_service.SongService.UpdateSongProcessingResult:input_type -> song_service.UpdateSongProcessingResultRequest
	16, // 17: song_service.SongService.AddFavorite:input_type -> song_service.FavoriteRequest
	16, // 18: song_service.SongService.RemoveFavorite:input_type -> song_service.FavoriteRequest
	19, // 19: song_service.SongService.GetPlaylist:input_type -> song_service.GetPlaylistRequest
	7,  // 20: song_service.SongService.GetSong:output_type -> song_service.GetSongResponse
	6,  // 21: song_service.SongService.GetSongByChecksum:output_type -> song_service.GetSongByChecksumResponse
	9,  // 22: song_service.SongService.GetSongIngestInfo:output_type -> song_service.GetSongIngestInfoResponse
	11, // 23: song_service.SongService.ListSongs:output_type -> song_service.ListSongsResponse
	13, // 24: song_service.SongService.CreateSongRecord:output_type -> song_service.CreateSongRecordResponse
	15, // 25: song_service.SongService.UpdateSongProcessingResult:output_type -> song_service.UpdateSongProcessingResultResponse
	17, // 26: song_service.SongService.AddFavorite:output_type -> song_service.FavoriteResponse
	17, // 27: song_service.SongService.RemoveFavorite:output_type -> song_service.FavoriteResponse
	20, // 28: song_service.SongService.GetPlaylist:output_type -> song_service.GetPlaylistResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_song_service_proto_init() }
func file_song_service_proto_init() {
	if File_song_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_song_service_proto_rawDesc), len(file_song_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_song_service_proto_goTypes,
		DependencyIndexes: file_song_service_proto_depIdxs,
		EnumInfos:         file_song_service_proto_enumTypes,
		MessageInfos:      file_song_service_proto_msgTypes,
	}.Build()
	File_song_service_proto = out.File
	file_song_service_proto_goTypes = nil
	file_song_service_proto_depIdxs = nil
}
