// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: song_service.proto

package song

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SongService_GetSong_FullMethodName                    = "/song_service.SongService/GetSong"
	SongService_GetSongByChecksum_FullMethodName          = "/song_service.SongService/GetSongByChecksum"
	SongService_GetSongIngestInfo_FullMethodName          = "/song_service.SongService/GetSongIngestInfo"
	SongService_ListSongs_FullMethodName                  = "/song_service.SongService/ListSongs"
	SongService_CreateSongRecord_FullMethodName           = "/song_service.SongService/CreateSongRecord"
	SongService_UpdateSongProcessingResult_FullMethodName = "/song_service.SongService/UpdateSongProcessingResult"
	SongService_AddFavorite_FullMethodName                = "/song_service.SongService/AddFavorite"
	SongService_RemoveFavorite_FullMethodName             = "/song_service.SongService/RemoveFavorite"
	SongService_GetPlaylist_FullMethodName                = "/song_service.SongService/GetPlaylist"
)

// SongServiceClient is the client API for SongService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Song service theo kiến trúc v5 (fMP4 + microservices)
type SongServiceClient interface {
	// Public read APIs
	GetSong(ctx context.Context, in *GetSongRequest, opts ...grpc.CallOption) (*GetSongResponse, error)
	GetSongByChecksum(ctx context.Context, in *GetSongByChecksumRequest, opts ...grpc.CallOption) (*GetSongByChecksumResponse, error)
	GetSongIngestInfo(ctx context.Context, in *GetSongIngestInfoRequest, opts ...grpc.CallOption) (*GetSongIngestInfoResponse, error)
	ListSongs(ctx context.Context, in *ListSongsRequest, opts ...grpc.CallOption) (*ListSongsResponse, error)
	// Ingest-oriented APIs
	CreateSongRecord(ctx context.Context, in *CreateSongRecordRequest, opts ...grpc.CallOption) (*CreateSongRecordResponse, error)
	UpdateSongProcessingResult(ctx context.Context, in *UpdateSongProcessingResultRequest, opts ...grpc.CallOption) (*UpdateSongProcessingResultResponse, error)
	// User library
	AddFavorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error)
	RemoveFavorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error)
	GetPlaylist(ctx context.Context, in *GetPlaylistRequest, opts ...grpc.CallOption) (*GetPlaylistResponse, error)
}

type songServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSongServiceClient(cc grpc.ClientConnInterface) SongServiceClient {
	return &songServiceClient{cc}
}

func (c *songServiceClient) GetSong(ctx context.Context, in *GetSongRequest, opts ...grpc.CallOption) (*GetSongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSongResponse)
	err := c.cc.Invoke(ctx, SongService_GetSong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) GetSongByChecksum(ctx context.Context, in *GetSongByChecksumRequest, opts ...grpc.CallOption) (*GetSongByChecksumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSongByChecksumResponse)
	err := c.cc.Invoke(ctx, SongService_GetSongByChecksum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) GetSongIngestInfo(ctx context.Context, in *GetSongIngestInfoRequest, opts ...grpc.CallOption) (*GetSongIngestInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSongIngestInfoResponse)
	err := c.cc.Invoke(ctx, SongService_GetSongIngestInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) ListSongs(ctx context.Context, in *ListSongsRequest, opts ...grpc.CallOption) (*ListSongsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSongsResponse)
	err := c.cc.Invoke(ctx, SongService_ListSongs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) CreateSongRecord(ctx context.Context, in *CreateSongRecordRequest, opts ...grpc.CallOption) (*CreateSongRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSongRecordResponse)
	err := c.cc.Invoke(ctx, SongService_CreateSongRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) UpdateSongProcessingResult(ctx context.Context, in *UpdateSongProcessingResultRequest, opts ...grpc.CallOption) (*UpdateSongProcessingResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSongProcessingResultResponse)
	err := c.cc.Invoke(ctx, SongService_UpdateSongProcessingResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) AddFavorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FavoriteResponse)
	err := c.cc.Invoke(ctx, SongService_AddFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) RemoveFavorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FavoriteResponse)
	err := c.cc.Invoke(ctx, SongService_RemoveFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) GetPlaylist(ctx context.Context, in *GetPlaylistRequest, opts ...grpc.CallOption) (*GetPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaylistResponse)
	err := c.cc.Invoke(ctx, SongService_GetPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SongServiceServer is the server API for SongService service.
// All implementations must embed UnimplementedSongServiceServer
// for forward compatibility.
//
// Song service theo kiến trúc v5 (fMP4 + microservices)
type SongServiceServer interface {
	// Public read APIs
	GetSong(context.Context, *GetSongRequest) (*GetSongResponse, error)
	GetSongByChecksum(context.Context, *GetSongByChecksumRequest) (*GetSongByChecksumResponse, error)
	GetSongIngestInfo(context.Context, *GetSongIngestInfoRequest) (*GetSongIngestInfoResponse, error)
	ListSongs(context.Context, *ListSongsRequest) (*ListSongsResponse, error)
	// Ingest-oriented APIs
	CreateSongRecord(context.Context, *CreateSongRecordRequest) (*CreateSongRecordResponse, error)
	UpdateSongProcessingResult(context.Context, *UpdateSongProcessingResultRequest) (*UpdateSongProcessingResultResponse, error)
	// User library
	AddFavorite(context.Context, *FavoriteRequest) (*FavoriteResponse, error)
	RemoveFavorite(context.Context, *FavoriteRequest) (*FavoriteResponse, error)
	GetPlaylist(context.Context, *GetPlaylistRequest) (*GetPlaylistResponse, error)
	mustEmbedUnimplementedSongServiceServer()
}

// UnimplementedSongServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSongServiceServer struct{}

func (UnimplementedSongServiceServer) GetSong(context.Context, *GetSongRequest) (*GetSongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSong not implemented")
}
func (UnimplementedSongServiceServer) GetSongByChecksum(context.Context, *GetSongByChecksumRequest) (*GetSongByChecksumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSongByChecksum not implemented")
}
func (UnimplementedSongServiceServer) GetSongIngestInfo(context.Context, *GetSongIngestInfoRequest) (*GetSongIngestInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSongIngestInfo not implemented")
}
func (UnimplementedSongServiceServer) ListSongs(context.Context, *ListSongsRequest) (*ListSongsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSongs not implemented")
}
func (UnimplementedSongServiceServer) CreateSongRecord(context.Context, *CreateSongRecordRequest) (*CreateSongRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSongRecord not implemented")
}
func (UnimplementedSongServiceServer) UpdateSongProcessingResult(context.Context, *UpdateSongProcessingResultRequest) (*UpdateSongProcessingResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSongProcessingResult not implemented")
}
func (UnimplementedSongServiceServer) AddFavorite(context.Context, *FavoriteRequest) (*FavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFavorite not implemented")
}
func (UnimplementedSongServiceServer) RemoveFavorite(context.Context, *FavoriteRequest) (*FavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFavorite not implemented")
}
func (UnimplementedSongServiceServer) GetPlaylist(context.Context, *GetPlaylistRequest) (*GetPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaylist not implemented")
}
func (UnimplementedSongServiceServer) mustEmbedUnimplementedSongServiceServer() {}
func (UnimplementedSongServiceServer) testEmbeddedByValue()                     {}

// UnsafeSongServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SongServiceServer will
// result in compilation errors.
type UnsafeSongServiceServer interface {
	mustEmbedUnimplementedSongServiceServer()
}

func RegisterSongServiceServer(s grpc.ServiceRegistrar, srv SongServiceServer) {
	// If the following call panics, it indicates UnimplementedSongServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SongService_ServiceDesc, srv)
}

func _SongService_GetSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).GetSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_GetSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).GetSong(ctx, req.(*GetSongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_GetSongByChecksum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSongByChecksumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).GetSongByChecksum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_GetSongByChecksum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).GetSongByChecksum(ctx, req.(*GetSongByChecksumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_GetSongIngestInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSongIngestInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).GetSongIngestInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_GetSongIngestInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).GetSongIngestInfo(ctx, req.(*GetSongIngestInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_ListSongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSongsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).ListSongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_ListSongs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).ListSongs(ctx, req.(*ListSongsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_CreateSongRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSongRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).CreateSongRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_CreateSongRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).CreateSongRecord(ctx, req.(*CreateSongRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_UpdateSongProcessingResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSongProcessingResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).UpdateSongProcessingResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_UpdateSongProcessingResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).UpdateSongProcessingResult(ctx, req.(*UpdateSongProcessingResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_AddFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).AddFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_AddFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).AddFavorite(ctx, req.(*FavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_RemoveFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).RemoveFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_RemoveFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).RemoveFavorite(ctx, req.(*FavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_GetPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).GetPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_GetPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).GetPlaylist(ctx, req.(*GetPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SongService_ServiceDesc is the grpc.ServiceDesc for SongService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SongService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "song_service.SongService",
	HandlerType: (*SongServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSong",
			Handler:    _SongService_GetSong_Handler,
		},
		{
			MethodName: "GetSongByChecksum",
			Handler:    _SongService_GetSongByChecksum_Handler,
		},
		{
			MethodName: "GetSongIngestInfo",
			Handler:    _SongService_GetSongIngestInfo_Handler,
		},
		{
			MethodName: "ListSongs",
			Handler:    _SongService_ListSongs_Handler,
		},
		{
			MethodName: "CreateSongRecord",
			Handler:    _SongService_CreateSongRecord_Handler,
		},
		{
			MethodName: "UpdateSongProcessingResult",
			Handler:    _SongService_UpdateSongProcessingResult_Handler,
		},
		{
			MethodName: "AddFavorite",
			Handler:    _SongService_AddFavorite_Handler,
		},
		{
			MethodName: "RemoveFavorite",
			Handler:    _SongService_RemoveFavorite_Handler,
		},
		{
			MethodName: "GetPlaylist",
			Handler:    _SongService_GetPlaylist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "song_service.proto",
}
