name = "music-streaming-edge"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
STREAM_COOKIE_NAME = "stream_auth"
STREAM_COOKIE_EXPIRY_SECONDS = "3600"
API_BASE_URL = "http://localhost:9999/api/v1"

[[r2_buckets]]
binding = "R2_PRODUCTION"
bucket_name = "music-hls-bucket"
remote = true

[[queues.consumers]]
queue = "upload-queue"