name = "edge-gateway"
main = "src/index.ts"
compatibility_date = "2026-05-01"
minify = true
workers_dev = false
preview_urls = false

[[r2_buckets]]
binding = "R2_PRODUCTION"
bucket_name = "music-hls-bucket"

[vars]
R2_CDN_URL = "https://r2.404hz.me"
KMS_URL = "https://marcus-pseudoscalar-unsurprisedly.ngrok-free.dev/api/v1/kms"