// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: key_management.proto

package kms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyRequest) Reset() {
	*x = GenerateKeyRequest{}
	mi := &file_key_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRequest) ProtoMessage() {}

func (x *GenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_management_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateKeyRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *GenerateKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type KeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	EncryptionKey []byte                 `protobuf:"bytes,2,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	Iv            []byte                 `protobuf:"bytes,3,opt,name=iv,proto3" json:"iv,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyResponse) Reset() {
	*x = KeyResponse{}
	mi := &file_key_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResponse) ProtoMessage() {}

func (x *KeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResponse.ProtoReflect.Descriptor instead.
func (*KeyResponse) Descriptor() ([]byte, []int) {
	return file_key_management_proto_rawDescGZIP(), []int{1}
}

func (x *KeyResponse) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *KeyResponse) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

func (x *KeyResponse) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *KeyResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_key_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_management_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeyRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

var File_key_management_proto protoreflect.FileDescriptor

const file_key_management_proto_rawDesc = "" +
	"\n" +
	"\x14key_management.proto\x12\x0ekey_management\"F\n" +
	"\x12GenerateKeyRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"|\n" +
	"\vKeyResponse\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\x12%\n" +
	"\x0eencryption_key\x18\x02 \x01(\fR\rencryptionKey\x12\x0e\n" +
	"\x02iv\x18\x03 \x01(\fR\x02iv\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"(\n" +
	"\rGetKeyRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId2\xb4\x01\n" +
	"\x14KeyManagementService\x12R\n" +
	"\x0fGenerateSongKey\x12\".key_management.GenerateKeyRequest\x1a\x1b.key_management.KeyResponse\x12H\n" +
	"\n" +
	"GetSongKey\x12\x1d.key_management.GetKeyRequest\x1a\x1b.key_management.KeyResponseB2Z0Music_Streaming_System/packages/shared-proto/kmsb\x06proto3"

var (
	file_key_management_proto_rawDescOnce sync.Once
	file_key_management_proto_rawDescData []byte
)

func file_key_management_proto_rawDescGZIP() []byte {
	file_key_management_proto_rawDescOnce.Do(func() {
		file_key_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_management_proto_rawDesc), len(file_key_management_proto_rawDesc)))
	})
	return file_key_management_proto_rawDescData
}

var file_key_management_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_key_management_proto_goTypes = []any{
	(*GenerateKeyRequest)(nil), // 0: key_management.GenerateKeyRequest
	(*KeyResponse)(nil),        // 1: key_management.KeyResponse
	(*GetKeyRequest)(nil),      // 2: key_management.GetKeyRequest
}
var file_key_management_proto_depIdxs = []int32{
	0, // 0: key_management.KeyManagementService.GenerateSongKey:input_type -> key_management.GenerateKeyRequest
	2, // 1: key_management.KeyManagementService.GetSongKey:input_type -> key_management.GetKeyRequest
	1, // 2: key_management.KeyManagementService.GenerateSongKey:output_type -> key_management.KeyResponse
	1, // 3: key_management.KeyManagementService.GetSongKey:output_type -> key_management.KeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_key_management_proto_init() }
func file_key_management_proto_init() {
	if File_key_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_management_proto_rawDesc), len(file_key_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_management_proto_goTypes,
		DependencyIndexes: file_key_management_proto_depIdxs,
		MessageInfos:      file_key_management_proto_msgTypes,
	}.Build()
	File_key_management_proto = out.File
	file_key_management_proto_goTypes = nil
	file_key_management_proto_depIdxs = nil
}
