// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ingestion_orchestrator.proto

package ingestion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StorageKey    string                 `protobuf:"bytes,3,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_ingestion_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *ProcessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProcessRequest) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_ingestion_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProcessResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_ingestion_orchestrator_proto protoreflect.FileDescriptor

const file_ingestion_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1cingestion_orchestrator.proto\x12\tingestion\"c\n" +
	"\x0eProcessRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vstorage_key\x18\x03 \x01(\tR\n" +
	"storageKey\"@\n" +
	"\x0fProcessResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2]\n" +
	"\x15IngestionOrchestrator\x12D\n" +
	"\vProcessSong\x12\x19.ingestion.ProcessRequest\x1a\x1a.ingestion.ProcessResponseB8Z6Music_Streaming_System/packages/shared-proto/ingestionb\x06proto3"

var (
	file_ingestion_orchestrator_proto_rawDescOnce sync.Once
	file_ingestion_orchestrator_proto_rawDescData []byte
)

func file_ingestion_orchestrator_proto_rawDescGZIP() []byte {
	file_ingestion_orchestrator_proto_rawDescOnce.Do(func() {
		file_ingestion_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_orchestrator_proto_rawDesc), len(file_ingestion_orchestrator_proto_rawDesc)))
	})
	return file_ingestion_orchestrator_proto_rawDescData
}

var file_ingestion_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ingestion_orchestrator_proto_goTypes = []any{
	(*ProcessRequest)(nil),  // 0: ingestion.ProcessRequest
	(*ProcessResponse)(nil), // 1: ingestion.ProcessResponse
}
var file_ingestion_orchestrator_proto_depIdxs = []int32{
	0, // 0: ingestion.IngestionOrchestrator.ProcessSong:input_type -> ingestion.ProcessRequest
	1, // 1: ingestion.IngestionOrchestrator.ProcessSong:output_type -> ingestion.ProcessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ingestion_orchestrator_proto_init() }
func file_ingestion_orchestrator_proto_init() {
	if File_ingestion_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_orchestrator_proto_rawDesc), len(file_ingestion_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_orchestrator_proto_goTypes,
		DependencyIndexes: file_ingestion_orchestrator_proto_depIdxs,
		MessageInfos:      file_ingestion_orchestrator_proto_msgTypes,
	}.Build()
	File_ingestion_orchestrator_proto = out.File
	file_ingestion_orchestrator_proto_goTypes = nil
	file_ingestion_orchestrator_proto_depIdxs = nil
}
