// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ingestion_orchestrator.proto

package ingestion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestionOrchestrator_ProcessSong_FullMethodName = "/ingestion.IngestionOrchestrator/ProcessSong"
)

// IngestionOrchestratorClient is the client API for IngestionOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestionOrchestratorClient interface {
	ProcessSong(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
}

type ingestionOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionOrchestratorClient(cc grpc.ClientConnInterface) IngestionOrchestratorClient {
	return &ingestionOrchestratorClient{cc}
}

func (c *ingestionOrchestratorClient) ProcessSong(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, IngestionOrchestrator_ProcessSong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestionOrchestratorServer is the server API for IngestionOrchestrator service.
// All implementations must embed UnimplementedIngestionOrchestratorServer
// for forward compatibility.
type IngestionOrchestratorServer interface {
	ProcessSong(context.Context, *ProcessRequest) (*ProcessResponse, error)
	mustEmbedUnimplementedIngestionOrchestratorServer()
}

// UnimplementedIngestionOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionOrchestratorServer struct{}

func (UnimplementedIngestionOrchestratorServer) ProcessSong(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessSong not implemented")
}
func (UnimplementedIngestionOrchestratorServer) mustEmbedUnimplementedIngestionOrchestratorServer() {}
func (UnimplementedIngestionOrchestratorServer) testEmbeddedByValue()                               {}

// UnsafeIngestionOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionOrchestratorServer will
// result in compilation errors.
type UnsafeIngestionOrchestratorServer interface {
	mustEmbedUnimplementedIngestionOrchestratorServer()
}

func RegisterIngestionOrchestratorServer(s grpc.ServiceRegistrar, srv IngestionOrchestratorServer) {
	// If the following call panics, it indicates UnimplementedIngestionOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionOrchestrator_ServiceDesc, srv)
}

func _IngestionOrchestrator_ProcessSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionOrchestratorServer).ProcessSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionOrchestrator_ProcessSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionOrchestratorServer).ProcessSong(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngestionOrchestrator_ServiceDesc is the grpc.ServiceDesc for IngestionOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestionOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingestion.IngestionOrchestrator",
	HandlerType: (*IngestionOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSong",
			Handler:    _IngestionOrchestrator_ProcessSong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingestion_orchestrator.proto",
}
